"""Closed failure enumeration and escalation mapping according to §14."""

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from myagentos.core.models.event import EventName


class FailureCode(StrEnum):
    """Closed enumeration of system failure classes (§14.1)."""

    SYNTAX_ERROR = "SYNTAX_ERROR"
    TEST_FAILURE = "TEST_FAILURE"
    CONTEXT_MISSING = "CONTEXT_MISSING"
    FLAKY_TEST = "FLAKY_TEST"
    ENVIRONMENT_ERROR = "ENVIRONMENT_ERROR"
    DEPENDENCY_ERROR = "DEPENDENCY_ERROR"
    POLICY_VIOLATION = "POLICY_VIOLATION"
    MERGE_CONFLICT = "MERGE_CONFLICT"
    REVIEW_REJECTED = "REVIEW_REJECTED"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    UNKNOWN = "UNKNOWN"


class FailureAction(StrEnum):
    """Actions decided by the Failure Classifier (§14.1)."""

    RETRY = "RETRY"
    CONTEXT_EXPANSION = "CONTEXT_EXPANSION"
    ENV_REPAIR = "ENV_REPAIR"
    ESCALATED = "ESCALATED"
    STOP = "STOP"


class FailureRule(BaseModel):
    """Policy rule associated with a failure code (§14.1)."""

    model_config = ConfigDict(frozen=True)

    default_action: FailureAction
    max_occurrences_per_job: int


FAILURE_ACTION_MAP: dict[FailureCode, FailureRule] = {
    FailureCode.SYNTAX_ERROR: FailureRule(
        default_action=FailureAction.RETRY,
        max_occurrences_per_job=2,
    ),
    FailureCode.TEST_FAILURE: FailureRule(
        default_action=FailureAction.RETRY,
        max_occurrences_per_job=4,
    ),
    FailureCode.CONTEXT_MISSING: FailureRule(
        default_action=FailureAction.CONTEXT_EXPANSION,
        max_occurrences_per_job=2,
    ),
    FailureCode.FLAKY_TEST: FailureRule(
        default_action=FailureAction.ESCALATED,
        max_occurrences_per_job=1,
    ),
    FailureCode.ENVIRONMENT_ERROR: FailureRule(
        default_action=FailureAction.ENV_REPAIR,
        max_occurrences_per_job=2,
    ),
    FailureCode.DEPENDENCY_ERROR: FailureRule(
        default_action=FailureAction.ESCALATED,
        max_occurrences_per_job=1,
    ),
    FailureCode.POLICY_VIOLATION: FailureRule(
        default_action=FailureAction.STOP,
        max_occurrences_per_job=0,
    ),
    FailureCode.MERGE_CONFLICT: FailureRule(
        default_action=FailureAction.STOP,
        max_occurrences_per_job=0,
    ),
    FailureCode.REVIEW_REJECTED: FailureRule(
        default_action=FailureAction.RETRY,
        max_occurrences_per_job=3,
    ),
    FailureCode.BUDGET_EXHAUSTED: FailureRule(
        default_action=FailureAction.STOP,
        max_occurrences_per_job=0,
    ),
    FailureCode.UNKNOWN: FailureRule(
        default_action=FailureAction.ESCALATED,
        max_occurrences_per_job=0,
    ),
}


class FailureRecord(BaseModel):
    """Detailed record of an encountered failure during job execution."""

    model_config = ConfigDict(frozen=True)

    code: FailureCode
    action: FailureAction
    message: str
    attempt: int = 1
    max_allowed: int
    diagnostics: dict[str, str] = Field(default_factory=dict)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))


class ObservedFailure(BaseModel):
    """Raw observable failure signals gathered from sandboxes, tools, or gates (§14.1)."""

    model_config = ConfigDict(frozen=True)

    stage: str = "UNKNOWN"
    exit_code: int = 1
    raw_output: str = ""
    error_type: str | None = None
    target_path: str | None = None
    command: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class JobLimits(BaseModel):
    """Hard limits enforced per job execution (§14.2)."""

    model_config = ConfigDict(frozen=True)

    max_attempts: int = 4
    max_usd: float = 10.0
    max_wallclock_seconds: float = 600.0
    stagnation_test_threshold: int = 2


class StagnationResult(BaseModel):
    """Result of stagnation detection analysis (§14.3)."""

    model_config = ConfigDict(frozen=True)

    stagnated: bool
    reason: str = ""
    consecutive_matches: int = 0


class HealingDecision(BaseModel):
    """Prescriptive healing decision generated by the HealingCoordinator (§14)."""

    model_config = ConfigDict(frozen=True)

    failure_record: FailureRecord
    action: FailureAction
    can_retry: bool
    fsm_event: EventName
    diagnostic_instructions: str
    retry_attempt: int

